-- TABELA DE PRODUTOS
CREATE TABLE PRODUTO (
  IDPRODUTO SERIAL PRIMARY KEY,
  FLAGINATIVO CHAR(1) NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  DESCRICAO TEXT
);

-- TABELA DE EMPRESAS
CREATE TABLE EMPRESA (
  IDEMPRESA SERIAL PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  CNPJ VARCHAR(14) NOT NULL,
  ENDERECO VARCHAR(100),
  TELEFONE VARCHAR(20)
);

-- TABELA DE USUÁRIOS
CREATE TABLE USUARIO (
  IDUSUARIO SERIAL PRIMARY KEY,
  IDEMPRESA INTEGER REFERENCES EMPRESA(IDEMPRESA),
  FLAGINATIVO CHAR(1) NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  SENHA VARCHAR(100) NOT NULL
);

-- TABELA DE CLIENTE_FORNECEDOR
CREATE TABLE CLIENTE_FORNECEDOR (
  IDCLIFOR SERIAL PRIMARY KEY,
  TIPOCLIFOR CHAR(1) NOT NULL,
  FLAGINATIVO CHAR(1) NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  CNPJCPF VARCHAR(14) NOT NULL,
  ENDERECO VARCHAR(100),
  TELEFONE VARCHAR(20)
);

-- TABELA DE COMPRAS E VENDAS
CREATE TABLE COMPRA_VENDA (
  IDMOVIMENTO INTEGER,
  IDUSUARIO INTEGER REFERENCES USUARIO(IDUSUARIO),
  IDPRODUTO INTEGER,
  IDCLIFOR INTEGER REFERENCES CLIENTE_FORNECEDOR(IDCLIFOR),
  IDEMPRESA INTEGER REFERENCES EMPRESA(IDEMPRESA),
  DATA_MOVIMENTO TIMESTAMP NOT NULL,
  QUANTIDADE NUMERIC(10, 2) DEFAULT 0,
  TIPOMOVIMENTO VARCHAR(2) NOT NULL, --C = COMPRA | V = VENDA | DC = DEV. COMPRA | DV = DEV. VENDA
  PRECO NUMERIC(10, 2) DEFAULT 0,
  PRIMARY KEY (IDMOVIMENTO, IDPRODUTO)
);

-- TABELA DE CONTROLE DO PREÇO DE VENDA
CREATE TABLE PRODUTO_PRECO_VENDA (
  IDPRODUTO INTEGER REFERENCES PRODUTO(IDPRODUTO),
  IDEMPRESA INTEGER REFERENCES EMPRESA(IDEMPRESA),
  PRECO NUMERIC(10, 2) DEFAULT 0
);

-- TABELA DE CONTROLE DE ESTOQUE
CREATE TABLE CONTROLE_ESTOQUE (
  IDPRODUTO INTEGER REFERENCES PRODUTO(IDPRODUTO),
  IDEMPRESA INTEGER REFERENCES EMPRESA(IDEMPRESA),
  QUANTIDADE INTEGER NOT NULL
);

-- TRIGGER QUE VAI INSERIR AUTOMATICAMENTE NA PRODUTO_PRECO_VENDA
CREATE OR REPLACE FUNCTION atualizar_preco_venda()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.TIPOMOVIMENTO = 'V' OR NEW.TIPOMOVIMENTO = 'DV' THEN
        PERFORM 1
        FROM PRODUTO_PRECO_VENDA
        WHERE IDPRODUTO = NEW.IDPRODUTO AND IDEMPRESA = NEW.IDEMPRESA;
        
        IF NOT FOUND THEN
            INSERT INTO PRODUTO_PRECO_VENDA (IDPRODUTO, IDEMPRESA, PRECO)
            VALUES (NEW.IDPRODUTO, NEW.IDEMPRESA, NEW.PRECO);
        ELSE
            UPDATE PRODUTO_PRECO_VENDA
            SET PRECO = NEW.PRECO
            WHERE IDPRODUTO = NEW.IDPRODUTO AND IDEMPRESA = NEW.IDEMPRESA;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- TRIGGER QUE VAI INSERIR AUTOMATICAMENTE NA CONTROLE_ESTOQUE
CREATE OR REPLACE FUNCTION atualizar_controle_estoque()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.TIPOMOVIMENTO = 'C' OR NEW.TIPOMOVIMENTO = 'DV' THEN
        PERFORM 1
        FROM CONTROLE_ESTOQUE
        WHERE IDPRODUTO = NEW.IDPRODUTO AND IDEMPRESA = NEW.IDEMPRESA;
        
        IF NOT FOUND THEN
            INSERT INTO CONTROLE_ESTOQUE (IDPRODUTO, IDEMPRESA, QUANTIDADE)
            VALUES (NEW.IDPRODUTO, NEW.IDEMPRESA, NEW.QUANTIDADE);
        ELSE
            UPDATE CONTROLE_ESTOQUE
            SET QUANTIDADE =  QUANTIDADE + NEW.QUANTIDADE
            WHERE IDPRODUTO = NEW.IDPRODUTO AND IDEMPRESA = NEW.IDEMPRESA;
        END IF;
    ELSEIF NEW.TIPOMOVIMENTO = 'V' OR NEW.TIPOMOVIMENTO = 'DC' THEN
		UPDATE CONTROLE_ESTOQUE
        SET QUANTIDADE =  QUANTIDADE - NEW.QUANTIDADE
        WHERE IDPRODUTO = NEW.IDPRODUTO AND IDEMPRESA = NEW.IDEMPRESA;
	END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- TRIGGER CHAMANDO A FUNC
CREATE TRIGGER trigger_atualizar_preco_venda
AFTER INSERT ON COMPRA_VENDA
FOR EACH ROW
EXECUTE FUNCTION atualizar_preco_venda();

-- TRIGGER CHAMANDO A FUNC
CREATE TRIGGER trigger_atualizar_controle_estoque
AFTER INSERT ON COMPRA_VENDA
FOR EACH ROW
EXECUTE FUNCTION atualizar_controle_estoque();

-- INSERÇÃO DE PRODUTOS
INSERT INTO PRODUTO (NOME, FLAGINATIVO, DESCRICAO)
VALUES ('ARROZ', 'F', 'ARROZ BRANCO');

INSERT INTO PRODUTO (NOME, FLAGINATIVO, DESCRICAO)
VALUES ('FEIJÃO', 'F', 'FEIJÃO CARIOCA');

INSERT INTO PRODUTO (NOME, FLAGINATIVO, DESCRICAO)
VALUES ('MACARRÃO', 'F', 'MACARRÃO ESPAGUETE');

INSERT INTO PRODUTO (NOME, FLAGINATIVO, DESCRICAO)
VALUES ('LEITE', 'F', 'LEITE INTEGRAL');

INSERT INTO PRODUTO (NOME, FLAGINATIVO, DESCRICAO)
VALUES ('PÃO DE FORMA', 'F', 'PÃO DE FORMA INTEGRAL');

INSERT INTO PRODUTO (NOME, FLAGINATIVO, DESCRICAO)
VALUES ('ÓLEO DE SOJA', 'F', 'ÓLEO DE SOJA REFINADO');

INSERT INTO PRODUTO (NOME, FLAGINATIVO, DESCRICAO)
VALUES ('CAFÉ', 'F', 'CAFÉ EM PÓ');

INSERT INTO PRODUTO (NOME, FLAGINATIVO, DESCRICAO)
VALUES ('AÇÚCAR', 'F', 'AÇÚCAR REFINADO');

INSERT INTO PRODUTO (NOME, FLAGINATIVO, DESCRICAO)
VALUES ('SAL', 'F', 'SAL REFINADO');

INSERT INTO PRODUTO (NOME, FLAGINATIVO, DESCRICAO)
VALUES ('FARINHA DE TRIGO', 'F', 'FARINHA DE TRIGO COMUM');

-- INSERÇÃO DE EMPRESAS
INSERT INTO EMPRESA (NOME, CNPJ, ENDERECO, TELEFONE)
VALUES ('EMPRESA A', '12345678901234', 'ENDEREÇO DA EMPRESA A', '46123456789');

INSERT INTO EMPRESA (NOME, CNPJ, ENDERECO, TELEFONE)
VALUES ('EMPRESA B', '98765432109876', 'ENDEREÇO DA EMPRESA B', '45987654321');

INSERT INTO EMPRESA (NOME, CNPJ, ENDERECO, TELEFONE)
VALUES ('EMPRESA C', '56789012345678', 'ENDEREÇO DA EMPRESA C', '47567890123');


-- INSERÇÃO DE USUÁRIOS
INSERT INTO USUARIO (NOME, FLAGINATIVO, IDEMPRESA, EMAIL, SENHA)
VALUES('ALBERTO', 'F', 1, 'A@A', '1');

INSERT INTO USUARIO (NOME, FLAGINATIVO, IDEMPRESA, EMAIL, SENHA)
VALUES ('MARIA SANTOS', 'F', 1, 'MARIA.SANTOS@EXAMPLE.COM', 'SENHA456');

INSERT INTO USUARIO (NOME, FLAGINATIVO, IDEMPRESA, EMAIL, SENHA)
VALUES ('PEDRO ALMEIDA', 'F', 1, 'PEDRO.ALMEIDA@EXAMPLE.COM', 'SENHA789');


-- INSERÇÃO DE CLIENTES_FORNECEDORES
INSERT INTO CLIENTE_FORNECEDOR (NOME, FLAGINATIVO, TIPOCLIFOR, CNPJCPF, ENDERECO, TELEFONE)
VALUES ('RENAN PINHEIRO', 'F', 'C', '12345677884', 'RUA A, 123', '551112345678');

INSERT INTO CLIENTE_FORNECEDOR (NOME, FLAGINATIVO, TIPOCLIFOR, CNPJCPF, ENDERECO, TELEFONE)
VALUES ('GABRIEL MENDES', 'F', 'C', '49512357881', 'RUA B, 456', '551198765432');

INSERT INTO CLIENTE_FORNECEDOR (NOME, FLAGINATIVO, TIPOCLIFOR, CNPJCPF, ENDERECO, TELEFONE)
VALUES ('ELISA CELINE', 'F', 'C', '02297843362', 'RUA C, 789', '551145678912');

INSERT INTO CLIENTE_FORNECEDOR (NOME, FLAGINATIVO, TIPOCLIFOR, CNPJCPF, ENDERECO, TELEFONE)
VALUES ('SUPERMERCADO A', 'F', 'F', '32198765400001', 'RUA D, 012', '551132109876');

INSERT INTO CLIENTE_FORNECEDOR (NOME, FLAGINATIVO, TIPOCLIFOR, CNPJCPF, ENDERECO, TELEFONE)
VALUES ('SUPERMERCADO B', 'F', 'F', '78945612300001', 'RUA E, 345', '551178945612');

INSERT INTO CLIENTE_FORNECEDOR (NOME, FLAGINATIVO, TIPOCLIFOR, CNPJCPF, ENDERECO, TELEFONE)
VALUES ('SUPERMERCADO C', 'F', 'F', '65432198700001', 'RUA F, 678', '551165432198');